# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

# Archivo: azure-pipelines.yml
trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  dockerRegistryServiceConnection: 'dockerHubServiceConnection'
  k8sServiceConnection: 'k8sServiceConnection'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Instalar dependencias'

- script: |
    pytest
  displayName: 'Ejecutar pruebas'

- task: Docker@2
  inputs:
    command: 'buildAndPush'
    repository: 'tu-usuario/proyecto-ahorcado'
    dockerfile: '**/Dockerfile'
    containerRegistry: '$(dockerRegistryServiceConnection)'
    tags: |
      $(Build.BuildId)
  displayName: 'Construir y subir imagen Docker'





